networks:
  nginx-front:
    driver: bridge
    external: false

services:
  vue-front-demo:
    image: nginx-example/vue-front:0.0.1
    container_name: vue-front-demo
    ports:
      - "80:80"
    networks:
      - nginx-front

